# This is a basic workflow to help you get started with Actions

name: Update engine

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set latest release branch
        id: set-engine
        run: |
          $branches = Invoke-RestMethod https://api.github.com/graphql -MaximumRetryCount 5 -Method POST -Body (@{
            query = '
            query {
              repository(name: "vscode", owner: "microsoft") {
                refs(refPrefix: "refs/heads/release/", first: 10, direction: DESC) {
                  edges {
                    node {
                      branchName: name
                    }
                  }
                }
              }
            }
            '
            } | ConvertTo-Json) -Headers @{ Authorization = "bearer ${{ github.token }}" }
            
          $branch = $branches.data.repository.refs.edges.node.branchName | Select-Object -First 1
          Write-Host "Latest VS Code stable: $branch"
          Write-Host "::set-output name=release_branch::$branch"
        shell: pwsh
